In [1]:
import fastf1
import pandas as pd

# Get the base directory path
fastf1.Cache.enable_cache('../data')  # Cache in /data

In [2]:
session = fastf1.get_session(2025, 'British Grand Prix', 'R')
session.load(weather=True)

core           INFO 	Loading data for British Grand Prix - Race [v3.5.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

In [3]:
session.weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:19.723000,18.0,85.0,988.6,False,24.2,174,0.7
1,0 days 00:01:19.675000,18.0,83.0,988.5,False,24.6,111,0.9
2,0 days 00:02:19.683000,18.1,82.0,988.6,False,24.6,61,2.2
3,0 days 00:03:19.685000,18.0,81.0,988.6,False,24.1,71,3.1
4,0 days 00:04:19.683000,18.0,79.0,988.5,False,23.9,28,3.0
...,...,...,...,...,...,...,...,...
150,0 days 02:30:20.275000,19.3,65.0,989.1,False,24.4,95,1.1
151,0 days 02:31:20.287000,19.4,64.0,989.0,False,24.4,230,1.9
152,0 days 02:32:20.278000,19.5,65.0,989.0,False,24.6,287,1.5
153,0 days 02:33:20.278000,19.5,64.0,989.0,False,24.6,48,1.6
154,0 days 02:34:20.295000,19.6,63.0,988.9,False,24.3,99,1.7

In [4]:
# filter the weather data rows which RainFall column is not False
rainfall = session.weather_data[session.weather_data['Rainfall'] != False]
rainfall

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
14,0 days 00:14:19.689000,18.3,78.0,988.7,True,24.0,82,1.2
15,0 days 00:15:19.688000,18.3,78.0,988.8,True,23.9,352,2.6
16,0 days 00:16:19.738000,18.3,77.0,988.6,True,22.6,319,1.0
17,0 days 00:17:19.694000,18.1,78.0,988.7,True,22.3,0,1.9
18,0 days 00:18:19.689000,18.1,79.0,988.7,True,21.8,6,1.0
19,0 days 00:19:19.686000,18.0,79.0,988.7,True,21.4,296,1.2
20,0 days 00:20:19.690000,17.8,81.0,988.6,True,21.4,18,2.0
21,0 days 00:21:19.709000,17.6,81.0,988.7,True,21.6,13,1.1
22,0 days 00:22:19.721000,17.6,82.0,988.8,True,21.7,15,1.0
23,0 days 00:23:19.732000,17.5,83.0,988.7,True,21.9,62,0.9
24,0 days 00:24:19.753000,17.5,84.0,988.8,True,21.9,94,0.7
25,0 days 00:25:19.760000,17.5,85.0,988.7,True,23.4,284,1.2
26,0 days 00:26:19.748000,17.4,85.0,988.8,True,22.3,69,1.1
27,0 days 00:27:19.756000,17.3,85.0,988.8,True,22.3,89,1.0
28,0 days 00:28:19.754000,17.3,85.0,988.7,True,22.8,52,1.7
29,0 days 00:29:19.762000,17.2,86.0,988.8,True,22.8,42,1.8
30,0 days 00:30:19.764000,17.2,86.0,988.8,True,22.2,72,0.5
76,0 days 01:16:19.959000,19.0,74.0,988.8,True,24.0,292,1.2
77,0 days 01:17:19.946000,18.9,73.0,988.8,True,23.3,105,1.1
78,0 days 01:18:19.969000,18.7,72.0,988.7,True,22.5,70,3.1
79,0 days 01:19:19.988000,18.5,72.0,988.6,True,21.5,69,5.8
80,0 days 01:20:19.992000,18.1,74.0,988.8,True,21.0,67,4.5
81,0 days 01:21:19.989000,17.8,77.0,988.8,True,20.5,65,3.9
82,0 days 01:22:19.989000,17.4,78.0,988.8,True,20.1,71,5.4
83,0 days 01:23:19.990000,17.1,80.0,988.9,True,20.0,75,4.2
84,0 days 01:24:19.987000,16.7,82.0,988.9,True,20.0,89,2.9
85,0 days 01:25:20.001000,16.5,83.0,988.9,True,20.2,63,3.0
86,0 days 01:26:19.997000,16.3,84.0,989.0,True,20.3,71,2.1